---
# tasks file for hostname

- name: host name
  block:
    - name: hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"
      tags:
        - hostname

    - name: /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '^[#\s]*127.0.1.1(\s+).*$'
        line:
          '127.0.1.1\1{{ ansible_nodename }}.{% if ansible_domain |
          length > 0 %}{{ ansible_domain }}{% else %}{{ domain_name }}
          {% endif %}
          {{ ansible_nodename }}'
        insertafter: '127.0.0.1\s+localhost'
        backrefs: true
        backup: true
      when:
        - hostname_lo_fqdn is defined
        - hostname_lo_fqdn
      tags:
        - hostname
        - hosts

  when: not ansible_virtualization_type | lower() in [ "lxc", "virtualpc" ]

- name: root gecos field
  ansible.builtin.user:
    name: root
    comment: "root@{{ inventory_hostname_short }}"
  when:
    - hostname_root_gecos_field is defined
    - hostname_root_gecos_field
  tags:
    - hostname
    - gecos
    - user
