---
# tasks file for hostname

- name: hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  when: not ansible_virtualization_type | lower() in ["lxc","virtualpc"]
  tags:
    - hostname

- name: root gecos field
  user:
    name: root
    comment: "root@{{ inventory_hostname_short }}"
  when: hostname_root_gecos_field
  tags:
    - hostname
    - gecos
    - user
